//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraficYborkiNomerov
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int etag { get; set; }
        public string gornichaia { get; set; }
    
        public virtual PostoialciGivushieSeichasVGostinice PostoialciGivushieSeichasVGostinice { get; set; }
    }
}
