//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_4.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GostinizaEntities : DbContext
    {
        private static GostinizaEntities _context;

        public static GostinizaEntities GetContext()
        {
            if (_context == null)
                _context = new GostinizaEntities();
            return _context;
        }

        public GostinizaEntities()
            : base("name=GostinizaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChetNaOplaty> ChetNaOplaty { get; set; }
        public virtual DbSet<GraficYborkiNomerov> GraficYborkiNomerov { get; set; }
        public virtual DbSet<nomer_fond> nomer_fond { get; set; }
        public virtual DbSet<OthetPoOplate> OthetPoOplate { get; set; }
        public virtual DbSet<OthetPoSostoianiuNomernogoFonda> OthetPoSostoianiuNomernogoFonda { get; set; }
        public virtual DbSet<PostoialciGivushieSeichasVGostinice> PostoialciGivushieSeichasVGostinice { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
