//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class nomer_fond
    {
        public int id { get; set; }
        public string aetag { get; set; }
        public int nomer { get; set; }
        public string kategoria { get; set; }
    
        public virtual OthetPoSostoianiuNomernogoFonda OthetPoSostoianiuNomernogoFonda { get; set; }
        public virtual PostoialciGivushieSeichasVGostinice PostoialciGivushieSeichasVGostinice { get; set; }
    }
}
